name: CI

on: [push]

jobs:
  tests:
    name: Tests ${{ matrix.php }}
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ranonkeltje
      MYSQL_PASSWORD: ranonkeltje
      MYSQL_DATABASE: aas2
      MYSQL_ROOT_PASSWORD: ranonkeltje

    strategy:
      matrix:
        php: ["7.3", "7.4"]
        experimental: [false]

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: ranonkeltje
          MYSQL_PASSWORD: ranonkeltje
          MYSQL_DATABASE: aas2
          MYSQL_ROOT_PASSWORD: ranonkeltje
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install composer dependencies
        run: composer install --prefer-dist --ignore-platform-reqs

      - name: Setup project
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          envsubst < .env.github > .env
          php artisan key:generate
          php artisan env
          php artisan migrate --seed

      - name: Run unit tests
        run: vendor/bin/phpunit

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/feature/github-actions'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install yarn dependencies
        run: yarn install

      - name: Compile assets
        run: yarn prod

      - name: Deploy assets
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_KEY }}
          source: "./public/js,./public/css,./public/fonts"
          target: "~/domains/anderwijs.nl/htdocs/aas2"

      - name: Deploy application
        uses: appleboy/ssh-action@master
        env:
          PHP_EXECUTABLE: php73
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_KEY }}
          envs: PHP_EXECUTABLE
          script: |
            cd ~/domains/anderwijs.nl/htdocs/aas2
            ${PHP_EXECUTABLE} artisan down
            git pull origin master
            ${PHP_EXECUTABLE} composer.phar self-update
            ${PHP_EXECUTABLE} composer.phar install
            ${PHP_EXECUTABLE} composer.phar dump-autoload
            ${PHP_EXECUTABLE} artisan clear-compiled
            ${PHP_EXECUTABLE} artisan optimize:clear
            ${PHP_EXECUTABLE} artisan migrate --force
            ${PHP_EXECUTABLE} artisan optimize
            ${PHP_EXECUTABLE} artisan up
